### ISSUE TITLE
Binary

### ISSUE THREAD

**Issue by nesdnuma** [maccallum/x#1]
Hello,

Is there a compiled version for Max/Win64 available somewhere?

**Comment by maccallum** [comment]
Hi, I wish there was, but I don’t have access to a Win development environment. If you know anyone who would be interested in working on a port, I’d be happy to help in any way I can.

John

**Comment by nesdnuma** [comment]
I'd be happy to do it. I have already built a few Max externals. With some guidance about the dependencies I think I could do it. By the way a friend of mine is also interested by a MacOS version.

**Comment by maccallum** [comment]
Cool, if you want to take a stab at the Win version, PM me and I can give you some details about how the Mac version is built. For your friend interested in the MacOS version, there are binaries on the [releases](https://github.com/maccallum/x/releases) page

**Comment by nesdnuma** [comment]
Hello, I've sent an e-mail to you about this. Maybe your e-mail client has considered it as spam? The e-mail was titled "Max X library Windows compilation".
